const field=(name,module,context)=>({
  name,
  definition: context || `${name} é uma decisão documentável dentro de ${module}; precisa ser específica o bastante para orientar escolhas reais.`,
  objective: `Transformar ${name} em critério claro de decisão, aplicação e revisão para a marca.`,
  questions:[`O que ${name} precisa tornar inequívoco nesta marca?`,`Que decisão prática muda quando ${name} está bem definido?`,`Que evidência, exemplo ou contraexemplo sustenta esta escolha?`],
  example:`Marca-exemplo — ${name}: decisão curta, específica e verificável, acompanhada de contexto e evidência quando aplicável.`,
  template:`${name}\nDecisão: [preencher]\nPor quê: [preencher]\nEvidência / fonte: [preencher]\nAplicações: [preencher]\nNão fazer: [preencher]`,
  presentation:`Apresente ${name} com uma decisão principal, evidência, exemplo e contraexemplo. A linguagem visual pode variar por marca, mas a leitura deve continuar rápida e comparável.`
});
const make=(number,id,title,group,summary,refs,names)=>({number,id,title,group,summary,why:summary,status:'Active',refs,fields:names.map(name=>field(name,title,contexts[name]))});
const contexts={
  'Arquétipo principal':'O padrão arquetípico dominante que orienta motivação, energia e decisões de expressão; não deve ser usado como rótulo decorativo.',
  'Proporção entre arquétipos':'A relação intencional entre arquétipo principal e secundário, indicando qual prevalece quando houver conflito.',
  'Escalas de personalidade':'Posiciona a marca em eixos comportamentais como Formal–Casual, Tradicional–Inovadora e Racional–Emocional.',
  'Voice':'A personalidade verbal estável da marca, independentemente do canal.',
  'Tone':'A variação contextual da voz conforme situação, emoção, risco e relação com o público.',
  'Tone of Voice':'A combinação operacional de voz, tom, vocabulário, ritmo e regras de escrita.',
  'Somos / Não somos':'Matriz de limites que define o traço desejado e o excesso que deve ser evitado.',
  'Antes / Depois':'Exemplos comparativos que demonstram como reescrever conteúdo genérico para soar como a marca.',
  'Big Idea':'A ideia central capaz de organizar comunicação, campanha e interpretação da marca sem depender de uma única frase.',
  'Reasons to Believe':'Evidências verificáveis que sustentam a promessa e reduzem a distância entre discurso e realidade.',
  'Logo Decision Tree':'Árvore de decisão que orienta qual versão do logo usar por espaço, fundo, produção e parceria.',
  'Brand Colors':'Visão geral da lógica cromática da marca, incluindo papel, proporção de uso e relações entre famílias.',
  'Primary Colors':'Cores com maior responsabilidade de reconhecimento e associação direta com a marca.',
  'Secondary Colors':'Cores de apoio usadas para ampliar expressão sem competir com a paleta principal.',
  'Neutral Colors':'Cores de equilíbrio editorial e suporte visual; continuam sendo parte da identidade, não tokens de interface.',
  'Supporting Colors':'Cores complementares de campanha, ilustração ou contexto com regras de proporção e restrição.',
  'Licenciamento e fontes oficiais':'Registra onde obter as fontes, licença, arquivos oficiais, formatos e restrições de redistribuição.',
  'This is us':'Conjunto de exemplos positivos que tornam critérios subjetivos visualmente verificáveis.',
  'This isn\'t us':'Conjunto de contraexemplos que explicitam o limite estético da marca.',
  'Reconhecimento sem logo':'Resposta operacional para a pergunta: o que torna a marca reconhecível quando o logo não aparece?',
  'Princípios invariáveis':'Elementos de essência, comportamento e expressão que permanecem consistentes em qualquer canal.',
  'Adaptação por canal':'Define o que pode variar por contexto sem alterar a identidade central.',
  'Brand System Prompt':'Prompt-base que resume essência, estratégia, personalidade, linguagem, restrições e critérios de avaliação.',
  'Evaluation Checklist':'Critérios para revisar se uma saída gerada por IA realmente pertence à marca.',
  'Brand Architecture':'Regras para organizar marca-mãe, produtos, programas, submarcas, extensões e parcerias.',
  'Research & Evidence':'Sistema de registro de fonte, data, método, confiança e hipótese para decisões estratégicas.',
  'Brand Measurement':'Indicadores, baseline e cadência para verificar se percepção e comportamento desejados estão ocorrendo.',
  'Accessibility & Inclusion':'Critérios para que expressão verbal, visual e audiovisual não exclua pessoas ou dependa de um único modo de percepção.',
  'Localization':'Define o que deve permanecer invariável e o que pode adaptar idioma, cultura, exemplos e convenções locais.',
  'Legal & Licensing':'Registra propriedade intelectual, permissões, licenças e restrições dos ativos de marca.'
};
const m4=make(4,'personality','Brand Personality','Foundation','Transforma traços abstratos em escolhas observáveis de comportamento, linguagem e expressão visual.',['github_attributes'],['Personalidade','Atributos','Arquétipo principal','Arquétipo secundário','Proporção entre arquétipos','Características','Comportamentos','Personalidade desejada','Comportamentos proibidos','Escalas de personalidade']);
const m5=make(5,'verbal-identity','Verbal Identity','Language & Narrative','Define como a marca escreve e fala de forma consistente em contextos, públicos e níveis de formalidade diferentes.',['github_voice','mailchimp_voice','mailchimp_principles','mailchimp_grammar','mailchimp_social','mailchimp_people'],['Voice','Tone','Tone of Voice','Voice Principles','Messaging Principles','Brand Vocabulary','Preferred Words','Forbidden Words','Expressions','Grammar','Punctuation','Capitalization','Emojis','English usage','Technical language','Humor','Calls to action','Headlines','Microcopy','UX Writing','Social Media','Advertising','Institutional Communication','Customer Support','Somos / Não somos','Antes / Depois']);
const m6=make(6,'messaging','Messaging System','Language & Narrative','Organiza a hierarquia de mensagens para que a marca diga a mesma coisa com profundidades e objetivos diferentes.',['github_voice','mailchimp_principles','mailchimp_structured'],['Brand Essence','Brand Promise','Big Idea','Tagline','Elevator Pitch','One-line description','25-word description','50-word description','Institutional description','About text','Boilerplate','Social bio','Sales message','Campaign message','Product message','CTA library','Mensagens principais','Mensagens secundárias','Provas','Benefícios funcionais','Benefícios emocionais','Reasons to Believe']);
const m7=make(7,'storytelling','Brand Storytelling','Language & Narrative','Define a narrativa que conecta origem, tensão, transformação, propósito e futuro sem inventar histórias que a marca não pode sustentar.',['github_getting','mailchimp_principles'],['Origem','Problema','Transformação','Visão de futuro','Fundador','História da marca','Histórias que a marca conta','Histórias que a marca não deve contar','Conflito','Propósito','Manifesto','Narrativa institucional']);
const m8=make(8,'visual-brand-identity','Visual Brand Identity','Visual Identity','Documenta o sistema de marca visual sem converter decisões de identidade em tokens ou componentes de produto.',['github_logo','github_foundations','github_cobrand','github_pdf','ibm_resources'],['Primary Logo','Secondary Logo','Symbol','Wordmark','Logo variations','Positive','Negative','Monochrome','Clear Space','Minimum Size','Background Usage','Incorrect Usage','Co-branding','Logo Decision Tree','Brand Colors','Primary Colors','Secondary Colors','Neutral Colors','Supporting Colors']);
const m9=make(9,'typography','Typography','Visual Identity','Define as famílias tipográficas da marca, suas funções, personalidade, hierarquia e combinações editoriais.',['ibm_type','ibm_plex','google_fonts'],['Primary Brand Typeface','Secondary Typeface','Display Typeface','Supporting Typeface','Função tipográfica','Personalidade tipográfica','Hierarquia','Combinações','Usos corretos','Usos incorretos','Licenciamento e fontes oficiais']);
const m10=make(10,'photography','Photography Direction','Visual Identity','Cria critérios objetivos para selecionar e produzir imagens que pareçam pertencer à marca antes mesmo de aplicar logo.',['ibm_photo','ibm_resources'],['Subjects','People','Environment','Lighting','Composition','Framing','Camera angle','Depth','Emotion','Color treatment','Texture','Authenticity','Scenarios','This is us','This isn\'t us','Direitos e releases']);
const m11=make(11,'illustration','Illustration','Visual Identity','Define uma linguagem ilustrativa reconhecível e reproduzível, com critérios para forma, personagens, perspectiva e acabamento.',['ibm_illustration','ibm_resources','github_graphic'],['Estilo','Formas','Traços','Proporções','Perspectiva','Personagens','Cores','Texturas','Sombras','Fundos','Composição','This is us','This isn\'t us','Licenciamento']);
const m12=make(12,'iconography','Iconography','Visual Identity','Documenta a assinatura de ícones da marca como linguagem visual, sem tratar ainda de biblioteca de interface.',['github_icon','ibm_icon','ibm_resources'],['Personalidade','Grid','Stroke','Corner style','Filled vs outline','Optical balance','Princípios visuais','Tamanhos de referência','Metáforas permitidas','Metáforas proibidas']);
const m13=make(13,'graphic-language','Graphic Language','Visual Identity','Constrói dispositivos proprietários que tornam a marca reconhecível mesmo sem o logo.',['github_graphic','ibm_philosophy'],['Shapes','Patterns','Frames','Lines','Textures','Gradients','Masks','Containers','Graphic devices','Decorative elements','Brand signatures','Reconhecimento sem logo']);
const m14=make(14,'layout','Layout Principles','Visual Identity','Define como a marca ocupa o espaço em composições editoriais, campanhas, social, apresentações e páginas institucionais.',['github_graphic','ibm_philosophy'],['Composição','Hierarquia','Alinhamento','Whitespace','Densidade','Equilíbrio','Proporção','Grids editoriais','Comportamento da marca no espaço','Social','Publicidade','Apresentações','Landing pages','Peças institucionais']);
const m15=make(15,'motion','Motion Identity','Visual Identity','Traduz a personalidade da marca em ritmo e movimento para narrativas, reveals e animações institucionais.',['ibm_motion','ibm_resources'],['Personalidade de movimento','Entrada','Saída','Transições','Logo animation','Brand reveals','Storytelling','Ritmo','Calm','Energetic','Precise','Playful','Elegant','Expressive','Do / Don\'t']);
const m16=make(16,'sonic','Sonic Identity','Experience','Módulo opcional para tornar som, voz e música parte coerente da identidade audiovisual da marca.',['ibm_motion'],['Sonic logo','Sound signature','Music direction','Voice','Notification personality','Podcast identity','Audiovisual direction','Licenciamento musical','Do / Don\'t']);
const m17=make(17,'brand-experience','Brand Experience','Experience','Mostra como a mesma essência se adapta a pontos de contato diferentes sem virar uma marca diferente em cada canal.',['github_getting','github_cobrand','mailchimp_voice'],['Website','Social','Advertising','Presentation','Email','Print','Packaging','Events','Environment','Customer Service','Sales','Partnerships','Princípios invariáveis','Adaptação por canal']);
const m18=make(18,'brand-in-action','Brand in Action','Experience','Explica o raciocínio por trás de aplicações reais para que exemplos funcionem como ensino, não só como mockup.',['github_getting','github_graphic'],['Campanha','Instagram','LinkedIn','Apresentação','Outdoor','Embalagem','Evento','Website','Anúncio','Material institucional','Raciocínio de aplicação','Checklist de consistência']);
const m19=make(19,'ai-guidelines','AI Brand Guidelines','AI & Governance','Converte a marca em instruções reutilizáveis por modelos de linguagem, agentes e ferramentas de geração de imagem.',['openai_prompt','openai_dev','mailchimp_voice'],['Brand System Prompt','Writing Prompt','Tone Prompt','Image Generation Prompt','Photography Prompt','Campaign Prompt','Social Prompt','Forbidden Styles','Forbidden Language','Brand Vocabulary','Negative Prompts','Examples','Evaluation Checklist','Versionamento de prompts']);
const m20=make(20,'governance','Brand Governance','AI & Governance','Trata a marca como sistema vivo com owners, aprovação, status, versões, evidências, licenças e histórico de mudança.',['github_getting','mailchimp_structured','wcag'],['Brand Owner','Design Owner','Marketing Owner','Approval Process','Brand Version','Last Update','Changelog','Stable','Beta','Experimental','Deprecated','Assets','Official Files','Naming Convention','Versioning','Brand Architecture','Naming System','Research & Evidence','Brand Measurement','Accessibility & Inclusion','Localization','Legal & Licensing']);
export default [m4,m5,m6,m7,m8,m9,m10,m11,m12,m13,m14,m15,m16,m17,m18,m19,m20];
