import { field, src, commonPresentation } from './shared.js';
export default [
field('Expressions','Expressões recorrentes, bordões ou construções proprietárias permitidas, com limites de repetição e contexto.','Criar assinatura verbal sem transformar a marca em personagem repetitivo.',['Que expressões soam naturais para a marca?','Em quais canais funcionam?','Com que frequência podem aparecer antes de virar clichê?'],'“Vamos ao que importa” pode abrir conteúdo explicativo, mas não deve aparecer em toda comunicação.','Expressão: [preencher]\nFunção: [preencher]\nContextos: [preencher]\nFrequência / limite: [preencher]\nEvitar quando: [preencher]',commonPresentation,src('gh','mailVoice')),
  field('Grammar','House style para estrutura de frase, voz verbal e decisões gramaticais recorrentes.','Eliminar decisões arbitrárias e tornar textos mais consistentes e legíveis.',['Preferimos voz ativa?','Como tratamos primeira e segunda pessoa?','Que estruturas de frase devemos favorecer?'],'Preferimos voz ativa, segunda pessoa quando apropriado e frases com uma ideia principal. Passiva só quando o agente não importa ou precisa ser omitido.','Voz verbal: [preencher]\nPessoa: [preencher]\nEstruturas preferidas: [preencher]\nExceções: [preencher]',commonPresentation,src('mailGrammar','msTop','govTone')),
  field('Punctuation','Convenções de pontuação que definem ritmo, clareza e consistência editorial.','Evitar que pontuação varie por gosto individual ou seja usada para “fabricar personalidade”.',['Usamos ponto em títulos?','Como tratamos exclamações, reticências, dois-pontos e travessões?','Qual pontuação deve ser rara?'],'Uma exclamação já é exceção. Reticências não são usadas para criar suspense institucional. Títulos priorizam leitura limpa.','Ponto final em títulos: [sim/não]\nExclamação: [regra]\nReticências: [regra]\nDois-pontos: [regra]\nTravessão: [regra]',commonPresentation,src('mailGrammar','msTop','govStyle')),
  field('Capitalization','Regras de caixa para títulos, produtos, áreas, botões, campanhas e termos proprietários.','Manter uma aparência verbal consistente e reduzir capitalização decorativa.',['Usamos sentence case ou title case?','Quais nomes são marcas registradas ou termos proprietários?','Que palavras nunca devem ser capitalizadas apenas por importância?'],'Sentence case como padrão. Nomes próprios e produtos seguem grafia oficial. Não capitalizamos palavras comuns para parecer mais importantes.','Padrão: [sentence/title case]\nProdutos: [regra]\nCampanhas: [regra]\nExceções: [preencher]',commonPresentation,src('mailGrammar','msTop','govStyle')),
  field('Emojis','Papel dos emojis na identidade verbal, incluindo frequência, categorias permitidas, acessibilidade e contextos proibidos.','Usar emoji como recurso sem depender dele para significado ou credibilidade.',['Em quais canais emojis são aceitáveis?','Quais combinam com a personalidade?','Quando um emoji reduz clareza, seriedade ou acessibilidade?'],'Permitidos com moderação em social e celebrações. Não substituem palavras essenciais, status, instruções ou comunicação de crise.','Canais permitidos: [preencher]\nFrequência: [preencher]\nPreferidos: [preencher]\nProibidos: [preencher]\nNunca substituir: [preencher]',commonPresentation,src('mailSocial','msBias')),
  field('English usage','Regra para uso de inglês dentro de conteúdo em português: termos técnicos, slogans, nomes próprios, categoria e linguagem de mercado.','Evitar mistura de idioma por moda e preservar compreensão sem apagar termos consolidados.',['Quando manter o termo em inglês?','Quando traduzir?','Como tratar termos sem equivalente preciso?'],'Use “briefing” se a audiência realmente usa o termo; prefira “entrar” a “login” em instruções gerais quando não houver necessidade técnica.','Termo em inglês: [preencher]\nManter/traduzir: [preencher]\nMotivo: [preencher]\nPrimeira ocorrência: [regra]',commonPresentation,src('msGlobal','govStyle')),
  field('Technical language','Regra para jargão, siglas, termos especializados e profundidade técnica por audiência.','Ser preciso sem usar complexidade como sinal de autoridade.',['Que termos técnicos a audiência já domina?','Quando definir uma sigla?','Como manter precisão ao simplificar?'],'Para especialistas, use o termo técnico correto. Para público amplo, explique na primeira ocorrência e priorize o efeito antes da implementação.','Termo: [preencher]\nAudiência que conhece: [preencher]\nExplicação curta: [preencher]\nQuando evitar: [preencher]',commonPresentation,src('msTop','govStyle','msGlobal')),
  field('Humor','Regras para quando, como e até onde a marca pode usar humor, ironia, referências culturais e brincadeiras.','Evitar humor fora de hora e manter humanidade sem comprometer confiança.',['Que tipo de humor combina com a personalidade?','Quem nunca deve ser alvo?','Quais situações anulam o humor?'],'Humor observacional leve é permitido. Nunca fazemos piada com erro do cliente, dinheiro perdido, segurança, crise, exclusão ou sofrimento.','Humor permitido: [preencher]\nAlvos proibidos: [preencher]\nContextos proibidos: [preencher]\nExemplo aprovado: [preencher]',commonPresentation,src('mailVoice','gh')),
];
