import { field, src, commonPresentation } from './shared.js';
export default [
field('Somos / Não somos','Matriz que define cada atributo verbal junto do excesso que precisa ser evitado. O lado negativo não é o oposto; é a sombra do traço desejado.','Criar guardrails memoráveis para revisão de texto.',['Qual é o excesso perigoso de cada atributo?','Que frase demonstra a diferença?','A equipe consegue usar esta matriz para revisar conteúdo?'],'Diretos / não grosseiros. Especialistas / não arrogantes. Próximos / não íntimos demais. Confiantes / não absolutos.','Somos: [traço]\nNão somos: [excesso]\nIsso significa: [regra prática]\nExemplo: [preencher]',commonPresentation,src('gh','mailVoice')),
  field('Antes / Depois','Pares de texto que mostram a transformação entre uma versão genérica ou inadequada e uma versão que incorpora a identidade verbal.','Ensinar o sistema por comparação, reduzindo interpretação subjetiva.',['Que problema existe no “antes”?','Que princípio resolve esse problema?','O “depois” preserva significado e melhora caráter?'],'Antes: “Nossa solução inovadora potencializa sua jornada.” Depois: “Veja o que mudou, por que importa e qual é o próximo passo.”','Antes: [texto]\nProblema: [preencher]\nDepois: [texto]\nPrincípios aplicados: [preencher]',commonPresentation,src('msTop','mailPrinciples')),
  field('Inclusive language & accessibility','Regras para linguagem respeitosa, compreensível e que evite pressupostos ou exclusões desnecessárias.','Fazer a identidade verbal funcionar para mais pessoas sem tratar inclusão como adendo opcional.',['Estamos pressupondo gênero, capacidade, origem ou contexto?','Há metáforas ou expressões que podem excluir?','A informação depende de jargão ou conhecimento não explicado?'],'Prefira referências neutras a pessoas e funções; escreva instruções que não dependam de cor, posição ou capacidade presumida.','Princípios inclusivos: [preencher]\nTermos preferidos: [preencher]\nTermos a evitar: [preencher]\nRevisão de acessibilidade: [preencher]',commonPresentation,src('msBias','govTone')),
  field('Localization & translation','Regras para escrever conteúdo que possa ser traduzido e adaptado culturalmente sem perder sentido, voz ou precisão.','Separar essência verbal do idioma e evitar textos impossíveis de localizar.',['Que expressões dependem de cultura local?','Quais termos não devem ser traduzidos?','Como simplificar estruturas para tradução?'],'Evite trocadilhos centrais em mensagens globais; mantenha uma lista de termos oficiais e permita adaptação cultural quando a intenção for mais importante que a literalidade.','Invariável: [preencher]\nPode adaptar: [preencher]\nNão traduzir: [preencher]\nGlossário: [preencher]\nValidação local: [preencher]',commonPresentation,src('msGlobal','govStyle')),
  field('Crisis & sensitive communication','Regras de linguagem para crise, segurança, interrupção, erro grave, temas sensíveis ou alto impacto.','Evitar humor, evasão, spin e excesso promocional quando confiança depende de clareza e responsabilidade.',['Que informação vem primeiro?','O que sabemos, não sabemos e estamos fazendo?','Que tom demonstra responsabilidade sem especular?'],'“Identificamos a falha às 14h20. O serviço está indisponível. Estamos trabalhando na recuperação e atualizaremos esta página às 15h.”','O que aconteceu: [preencher]\nImpacto: [preencher]\nO que sabemos: [preencher]\nO que não sabemos: [preencher]\nPróxima atualização: [preencher]',commonPresentation,src('msVoice','govTone')),
  field('Readability & editing','Critérios de edição para remover excesso, priorizar informação, revisar legibilidade e manter a voz após múltiplas aprovações.','Fazer cada texto chegar à versão final mais clara, curta e fiel à intenção.',['Qual é a ideia principal?','Que palavras podem sair sem perda?','O texto funciona ao ser lido em voz alta?','Existe uma frase mais específica e simples?'],'Primeiro corte 30% do texto; depois verifique se cada parágrafo tem uma função; por fim revise termos, tom, prova e acessibilidade.','Objetivo do texto: [preencher]\nMensagem principal: [preencher]\nCortes realizados: [preencher]\nChecklist final: [preencher]',commonPresentation,src('msTop','mailPrinciples','govTone'))
];
