import { field, src, commonPresentation } from './shared.js';
export default [
field('Calls to action','Sistema verbal para CTAs conforme intenção: começar, explorar, aprender, comparar, pedir ajuda, comprar ou confirmar.','Criar ações claras, específicas e coerentes com a voz.',['O CTA descreve a ação real?','O verbo cria expectativa correta sobre o próximo passo?','Estamos usando urgência artificial?'],'Preferimos “Ver opções”, “Criar projeto”, “Falar com especialista” e “Baixar guia” a “Saiba mais” quando existe uma ação mais específica.','Intenção: [preencher]\nCTA principal: [preencher]\nAlternativas: [preencher]\nEvitar: [preencher]',commonPresentation,src('msTop','mailPrinciples')),
  field('Headlines','Princípios para títulos de campanha, institucional, editorial e conteúdo explicativo.','Fazer a primeira linha carregar ideia, benefício ou tensão sem depender de subtítulo genérico.',['O título diz algo específico?','A ideia continua compreensível fora do layout?','É uma promessa que conseguimos sustentar?'],'“Decida com contexto, não com ruído.” em vez de “Uma nova forma de transformar o futuro”.','Função: [campanha/institucional/editorial]\nHeadline: [preencher]\nIdeia principal: [preencher]\nProva / suporte: [preencher]',commonPresentation,src('msTop','mailPrinciples')),
  field('Microcopy','Textos curtos que orientam ações, confirmações, estados e pequenas decisões em experiências digitais ou materiais de marca.','Manter clareza e personalidade em espaços reduzidos sem sacrificar função.',['Qual é a informação mínima necessária?','O texto deixa a próxima ação clara?','A personalidade está ajudando ou atrapalhando a tarefa?'],'“Arquivo salvo. Você pode continuar editando.” é preferível a “Oba! Tudo prontinho por aqui 🎉” em um contexto funcional neutro.','Situação: [preencher]\nMensagem: [preencher]\nAção seguinte: [preencher]\nTom: [preencher]',commonPresentation,src('msTop','mailPrinciples')),
  field('UX Writing','Princípios para linguagem aplicada a jornadas, instruções, erros, confirmações e decisões de uso, ainda documentados como expressão verbal da marca.','Garantir que a voz sobreviva aos pontos de contato funcionais sem transformar esta etapa em Design System.',['A instrução ajuda a pessoa a avançar?','Erros explicam o que ocorreu e o que fazer?','O tom respeita o estado emocional da pessoa?'],'Erro: “Não conseguimos enviar agora. Tente novamente em alguns minutos.” Evite “Oops! Algo deu errado 😅” em falhas relevantes.','Contexto: [preencher]\nNecessidade da pessoa: [preencher]\nTexto: [preencher]\nAção seguinte: [preencher]\nTom: [preencher]',commonPresentation,src('msVoice','mailVoice','govTone')),
  field('Social Media','Regras de voz, ritmo, interação, comentário, resposta, tendências e adaptação cultural para redes sociais.','Permitir mais espontaneidade sem descaracterizar ou tornar a marca refém de tendências.',['Como respondemos comentários?','Que tendências são coerentes?','Qual nível de informalidade é aceitável?'],'Podemos ser mais rápidos e leves, mas não imitar gírias que a marca não usa nem “entrar em trends” sem relação com nosso território.','Plataforma: [preencher]\nTom base: [preencher]\nPode aumentar: [preencher]\nNunca: [preencher]\nExemplo: [preencher]',commonPresentation,src('mailSocial','gh')),
  field('Advertising','Regras para linguagem persuasiva, headlines, provas, urgência, ofertas e claims em publicidade.','Aumentar força comercial sem abandonar verdade, precisão ou personalidade.',['Que tipo de promessa a marca pode fazer?','Como usamos prova?','Que recursos de pressão são proibidos?'],'Use benefício específico e evidência. Não invente escassez, medo ou certeza absoluta para forçar conversão.','Objetivo: [preencher]\nClaim: [preencher]\nProva: [preencher]\nCTA: [preencher]\nLimites: [preencher]',commonPresentation,src('gh','mailPrinciples')),
  field('Institutional Communication','Tom para apresentações corporativas, imprensa, relatórios, parceiros, liderança e comunicação oficial.','Manter autoridade sem burocratizar a voz.',['O que precisa soar mais formal?','Que termos corporativos podemos eliminar?','Como preservar humanidade sem perder precisão?'],'“Neste trimestre, reduzimos X porque…” em vez de “No âmbito de nossa estratégia de excelência operacional…”.','Audiência: [preencher]\nObjetivo: [preencher]\nFormalidade: [preencher]\nEstrutura: [preencher]\nTermos a evitar: [preencher]',commonPresentation,src('msVoice','govTone')),
  field('Customer Support','Tom para ajuda, conflito, falha, frustração, reembolso, espera e resolução.','Proteger confiança em momentos de maior carga emocional.',['Como reconhecemos frustração sem dramatizar?','Quando pedir desculpas?','Como comunicar limite sem culpar a pessoa?'],'“Entendo o impacto. O pagamento não foi concluído e nenhum valor foi cobrado. Tente novamente ou fale com a gente.”','Situação: [preencher]\nEstado provável: [preencher]\nReconhecer: [preencher]\nExplicar: [preencher]\nPróximo passo: [preencher]',commonPresentation,src('mailVoice','msVoice')),
];
