import { field, src, commonPresentation } from './shared.js';
export default [
field('Voice','A personalidade verbal estável da marca: o conjunto de qualidades que deve permanecer reconhecível independentemente de canal ou situação.','Traduzir Brand Personality em uma forma consistente de falar e escrever.',['Quais 3–5 qualidades precisam ser reconhecidas em qualquer texto?','Como essas qualidades aparecem em escolhas linguísticas observáveis?','Que voz seria incompatível com a personalidade da marca?'],'Horizonte fala com clareza, autoridade tranquila e proximidade adulta. Explica sem exibir conhecimento e assume posição sem soar absoluta.','Voice em uma frase: [preencher]\nQualidades invariáveis: [preencher]\nComo aparecem na escrita: [preencher]\nNunca soa como: [preencher]',commonPresentation,src('gh','mailVoice','msVoice'),'Auditoria de conteúdo, pesquisa de percepção e exemplos reais da marca.'),
  field('Tone','A variação contextual da voz conforme objetivo, risco, emoção, canal e estado da audiência. A voz permanece; a intensidade dos traços muda.','Permitir adaptação sem criar uma personalidade diferente em cada canal.',['Que fatores fazem o tom mudar?','O que aumenta ou diminui em campanha, suporte, crise e institucional?','Que elemento da voz nunca muda?'],'Em suporte crítico: menos humor, mais calma e instrução. Em campanha: mais energia e imaginação. Em institucional: mais autoridade, sem frieza.','Contexto: [preencher]\nEstado da audiência: [preencher]\nAumenta: [preencher]\nReduz: [preencher]\nInvariáveis: [preencher]',commonPresentation,src('mailVoice','msVoice','govTone')),
  field('Tone of Voice','Sistema operacional que combina voice, tone, vocabulário, ritmo, sintaxe, mecânica e limites de linguagem.','Transformar “como falamos” em regras utilizáveis por qualquer pessoa, canal ou parceiro.',['Quais decisões de linguagem compõem nosso tom de voz?','Que regras são invariáveis e quais dependem de contexto?','Como alguém valida se um texto pertence à marca?'],'Direto, humano e criterioso: frases curtas, verbos ativos, pouco jargão, claims verificáveis e humor apenas quando não reduz a seriedade da situação.','Voice: [preencher]\nTone rules: [preencher]\nVocabulário: [preencher]\nRitmo: [preencher]\nMecânica: [preencher]\nGuardrails: [preencher]',commonPresentation,src('mailVoice','mailGrammar','msVoice')),
  field('Voice Principles','Princípios que convertem a voz em decisões repetíveis de escrita. Devem ser poucos, claros e acompanhados de “faça / evite”.','Dar critérios de aprovação mais úteis do que adjetivos isolados.',['Quais princípios orientam 80% das decisões?','Como cada princípio muda uma frase?','Qual excesso deve ser evitado?'],'1. Comece pelo essencial. 2. Explique sem infantilizar. 3. Seja confiante sem parecer absoluto. 4. Escreva para pessoas, não para parecer institucional.','Princípio: [preencher]\nFaça: [preencher]\nEvite: [preencher]\nExemplo: [preencher]\nContraexemplo: [preencher]',commonPresentation,src('mailPrinciples','msTop','govTone')),
  field('Messaging Principles','Regras de construção de mensagem que definem prioridade, ordem e evidência sem substituir o Messaging System.','Garantir que forma e substância trabalhem juntas: o conteúdo precisa soar como a marca e dizer o que importa.',['Começamos pela necessidade, benefício ou pela marca?','Quando precisamos provar um claim?','Como lidamos com incerteza e limitação?'],'Comece pelo valor para a pessoa; explique a ação; prove afirmações relevantes; deixe limitações visíveis antes de detalhes promocionais.','Princípio de mensagem: [preencher]\nPrioridade: [preencher]\nProva necessária: [preencher]\nQuando usar: [preencher]',commonPresentation,src('mailPrinciples','msTop')),
  field('Brand Vocabulary','Vocabulário proprietário ou recorrente que reforça estratégia, categoria e personalidade sem criar jargão desnecessário.','Criar consistência lexical e facilitar reconhecimento verbal.',['Que palavras expressam nossa visão de mundo?','Que termos precisam ter definição oficial?','Que palavras são exclusivas da marca e quais são linguagem comum?'],'Preferimos “clareza”, “contexto”, “decisão” e “progresso” quando são verdadeiros. Não transformamos cada conceito em nome proprietário.','Termo: [preencher]\nDefinição oficial: [preencher]\nQuando usar: [preencher]\nQuando não usar: [preencher]\nExemplo: [preencher]',commonPresentation,src('govStyle','mailGrammar')),
  field('Preferred Words','Lista de palavras e construções preferidas porque refletem clareza, posicionamento ou linguagem do público.','Reduzir variação desnecessária e acelerar revisão editorial.',['Qual termo a audiência entende melhor?','Qual alternativa soa mais humana e específica?','Existe razão de marca ou pesquisa para a preferência?'],'Use “começar”, não “iniciar jornada”; “ajuda”, não “suporte especializado” quando o contexto não exige tecnicidade.','Preferimos: [termo]\nEm vez de: [alternativa]\nPorque: [motivo]\nExemplo: [frase]',commonPresentation,src('govStyle','msTop')),
  field('Forbidden Words','Termos proibidos ou altamente restritos por incoerência, exagero, risco legal, exclusão, clichê ou falta de precisão.','Evitar linguagem que destrua confiança ou descaracterize a marca.',['Quais clichês de categoria queremos eliminar?','Que palavras prometem mais do que podemos provar?','Que termos são excludentes ou culturalmente problemáticos?'],'Evitar “revolucionário”, “sem esforço”, “garantido” e “para todo mundo” quando não houver evidência ou precisão suficiente.','Termo proibido: [preencher]\nMotivo: [preencher]\nAlternativa: [preencher]\nExceção aprovada: [se houver]',commonPresentation,src('govStyle','msBias')),
];
