import { groups, esc, num, markdownModule, frameworkRefs } from './brand-ui.js';
import { overviewPage, modulePage } from './brand-pages.js';
import { audienceExtras, bindAudienceExtras } from './audience.js';
import { personalityExtras, bindPersonalityExtras } from './personality.js';
import { verbalExtras, bindVerbalExtras } from './verbal.js';

const app=document.getElementById('app'),nav=document.getElementById('nav'),pageTitle=document.getElementById('pageTitle'),navSearch=document.getElementById('navSearch'),themeButton=document.getElementById('themeButton'),menuButton=document.getElementById('menuButton'),drawerClose=document.getElementById('drawerClose'),backdrop=document.getElementById('backdrop'),downloadAll=document.getElementById('downloadAll'),sidebar=document.getElementById('sidebar'),toast=document.getElementById('toast');
const mobile=window.matchMedia('(max-width:760px)');
let data={modules:[],references:{},resources:{}},selectedField=0,selectedTab='definition';
const route=()=>{const raw=location.hash.replace(/^#\//,'')||'overview',[type,id]=raw.split('/');return type==='module'?{type,id}:{type:'overview'}};
const moduleById=id=>data.modules.find(m=>String(m.id)===String(id));
function notify(t){toast.textContent=t;toast.classList.add('show');clearTimeout(notify.t);notify.t=setTimeout(()=>toast.classList.remove('show'),1400)}
function setDrawer(open,restore=false){document.body.classList.toggle('nav-open',open&&mobile.matches);menuButton.setAttribute('aria-expanded',String(open&&mobile.matches));sidebar.setAttribute('aria-hidden',String(mobile.matches&&!open));if('inert'in sidebar)sidebar.inert=mobile.matches&&!open;if(!open&&restore)menuButton.focus()}
function save(name,content,type='text/plain'){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),500)}
async function copy(text){if(navigator.clipboard)await navigator.clipboard.writeText(text);else notify('Clipboard indisponível');notify('Copiado')}
function renderNav(filter=''){const r=route(),term=filter.trim().toLowerCase(),mods=data.modules.filter(m=>!term||[m.title,m.summary,...(m.fields||[]).map(f=>f.name)].join(' ').toLowerCase().includes(term));nav.innerHTML=`<div class="nav-group"><div class="nav-title">Start</div><a class="nav-link ${r.type==='overview'?'active':''}" href="#/overview"><span>00</span><strong>Overview</strong></a></div>`+groups.map(([label,min,max])=>{const list=mods.filter(m=>Number(m.number)>=min&&Number(m.number)<=max);return list.length?`<div class="nav-group"><div class="nav-title">${esc(label)}</div>${list.map(m=>`<a class="nav-link ${r.type==='module'&&r.id===m.id?'active':''}" href="#/module/${esc(m.id)}"><span>${num(m)}</span><strong>${esc(m.title)}</strong></a>`).join('')}</div>`:''}).join('');nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>mobile.matches&&setDrawer(false)))}
function bind(module){app.querySelectorAll('[data-field]').forEach(b=>b.addEventListener('click',()=>{selectedField=+b.dataset.field;selectedTab='definition';render(false)}));app.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{selectedTab=b.dataset.tab;render(false)}));const search=document.getElementById('fieldSearch');if(search)search.addEventListener('input',()=>{const t=search.value.toLowerCase();app.querySelectorAll('.field-button').forEach(b=>b.hidden=!b.textContent.toLowerCase().includes(t))});if(!module)return;const current=module.fields?.[selectedField]||module.fields?.[0];app.querySelector('[data-copy-field]')?.addEventListener('click',e=>copy(e.currentTarget.dataset.copyField==='example'?current.example||'':current.template||''));app.querySelector('[data-download="json"]')?.addEventListener('click',()=>save(`${module.extras?.downloadName||num(module)+'-'+module.id}.json`,JSON.stringify(module,null,2),'application/json'));app.querySelector('[data-download="md"]')?.addEventListener('click',()=>save(`${module.extras?.downloadName||num(module)+'-'+module.id}.md`,markdownModule(module),'text/markdown'));app.querySelector('[data-copy-module]')?.addEventListener('click',()=>copy(markdownModule(module)));bindAudienceExtras(app,module);bindPersonalityExtras(app,module,{save,copy,notify});bindVerbalExtras(app,module,{save,copy,notify})}
function render(scroll=true){const r=route(),module=r.type==='module'?moduleById(r.id):null;if(r.type==='module'&&!module){location.hash='#/overview';return}if(module&&selectedField>=(module.fields?.length||0))selectedField=0;pageTitle.textContent=module?`${num(module)} — ${module.title}`:'Overview';document.title=`${pageTitle.textContent} · Brand Framework`;app.innerHTML=module?modulePage(module,data,selectedField,selectedTab)+audienceExtras(module)+personalityExtras(module)+verbalExtras(module):overviewPage(data);renderNav(navSearch.value);bind(module);if(scroll){app.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'})}}
async function init(){try{const res=await fetch('./brand-data.json',{cache:'no-store'});if(!res.ok)throw new Error(`HTTP ${res.status}`);data=await res.json();if(!Array.isArray(data.modules)||data.modules.length<20)throw new Error('Brand data incompleto');data.frameworkRefs=frameworkRefs(data);render()}catch(error){console.error(error);app.innerHTML=`<header class="hero"><p class="eyebrow">Build error</p><h1>Não foi possível carregar o Brand Framework.</h1><p class="lead">${esc(error.message)}</p></header>`}}
window.addEventListener('hashchange',()=>{selectedField=0;selectedTab='definition';render()});navSearch.addEventListener('input',()=>renderNav(navSearch.value));menuButton.addEventListener('click',()=>setDrawer(true));drawerClose.addEventListener('click',()=>setDrawer(false,true));backdrop.addEventListener('click',()=>setDrawer(false));document.addEventListener('keydown',e=>e.key==='Escape'&&setDrawer(false,true));mobile.addEventListener('change',()=>setDrawer(false));themeButton.addEventListener('click',()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;localStorage.setItem('brand-theme',next)});const saved=localStorage.getItem('brand-theme');if(saved==='dark'||saved==='light')document.documentElement.dataset.theme=saved;downloadAll.addEventListener('click',()=>save('brand-framework.json',JSON.stringify({version:'1.3.0',exportedAt:new Date().toISOString(),modules:data.modules},null,2),'application/json'));setDrawer(false);init();
