import { esc } from './brand-ui.js';

const state=new Map();
const safeItems=v=>Array.isArray(v)?v:[];
const studioFor=module=>module?.extras?.studio;
const key=m=>`brand-studio:${m.id}`;

function renderSteps(view){return `<div class="studio-steps">${safeItems(view.items).map((x,i)=>`<article><span>${String(i+1).padStart(2,'0')}</span><div><strong>${esc(x.title)}</strong><p>${esc(x.text||'')}</p></div></article>`).join('')}</div>`}
function renderCards(view){return `<div class="studio-cards">${safeItems(view.items).map(x=>`<article><strong>${esc(x.title)}</strong><p>${esc(x.text||'')}</p>${x.text?`<button type="button" data-studio-copy="${encodeURIComponent(x.text)}">Copiar</button>`:''}</article>`).join('')}</div>`}
function renderMatrix(view){return `<div class="studio-table-wrap"><table class="studio-table"><thead><tr>${safeItems(view.columns).map(c=>`<th>${esc(c)}</th>`).join('')}</tr></thead><tbody>${safeItems(view.rows).map(row=>`<tr>${safeItems(row).map(cell=>`<td>${esc(cell)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function renderChecklist(view,module){const saved=state.get(module.id)||{};return `<div class="studio-checklist">${safeItems(view.items).map((x,i)=>`<label><input type="checkbox" data-studio-check="${view.id}:${i}" ${saved[`${view.id}:${i}`]?'checked':''}/><span>${esc(x)}</span></label>`).join('')}</div>`}
function renderResources(view){return `<div class="studio-resources">${safeItems(view.items).map(x=>`<article><div><strong>${esc(x.title)}</strong><p>${esc(x.note||'')}</p><small>${esc(x.kind||'Resource')}</small></div><a href="${esc(x.url)}" target="_blank" rel="noreferrer">Abrir / baixar ↗</a></article>`).join('')}</div>`}
function renderPrompt(view){return `<div class="studio-prompts">${safeItems(view.items).map(x=>`<article><div><strong>${esc(x.title)}</strong><button type="button" data-studio-copy="${encodeURIComponent(x.text||'')}">Copiar</button></div><pre>${esc(x.text||'')}</pre></article>`).join('')}</div>`}
function renderPalette(view){return `<div class="studio-palette">${safeItems(view.items).map(x=>`<article><div class="studio-swatch" style="background:${esc(x.hex)}"></div><div><strong>${esc(x.title)}</strong><p>${esc(x.use||'')}</p><dl>${[['HEX',x.hex],['RGB',x.rgb],['CMYK',x.cmyk],['Pantone',x.pantone],['OKLCH',x.oklch]].map(([k,v])=>`<div><dt>${k}</dt><dd><code>${esc(v||'—')}</code>${v?`<button type="button" data-studio-copy="${encodeURIComponent(v)}">Copiar</button>`:''}</dd></div>`).join('')}</dl></div></article>`).join('')}</div>`}
function renderDecision(view){return `<div class="studio-decision">${safeItems(view.questions).map((q,i)=>`<article><span>${String(i+1).padStart(2,'0')}</span><strong>${esc(q.label)}</strong><div><button type="button" data-decision-result="${encodeURIComponent(q.yes||'')}" data-decision-index="${i}">Sim</button><button type="button" data-decision-result="${encodeURIComponent(q.no||'')}" data-decision-index="${i}">Não</button></div><p data-decision-output="${i}">Escolha uma resposta.</p></article>`).join('')}</div>`}
function renderView(view,module){switch(view.type){case'steps':return renderSteps(view);case'cards':return renderCards(view);case'matrix':return renderMatrix(view);case'checklist':return renderChecklist(view,module);case'resources':return renderResources(view);case'prompt':return renderPrompt(view);case'palette':return renderPalette(view);case'decision':return renderDecision(view);default:return renderCards(view)}}

export function moduleStudio(module){const studio=studioFor(module);if(!studio)return'';const views=safeItems(studio.views);if(!views.length)return'';return `<section class="section brand-studio" data-studio-module="${esc(module.id)}"><div class="section-head"><div><p class="eyebrow">Brand Studio</p><h2>${esc(studio.title||'Module Studio')}</h2></div><p>${esc(studio.intro||'Ferramenta interativa do módulo.')}</p></div><div class="studio-tabs" role="tablist">${views.map((v,i)=>`<button type="button" class="studio-tab ${i===0?'active':''}" data-studio-tab="${esc(v.id)}">${esc(v.label||v.id)}</button>`).join('')}</div>${views.map((v,i)=>`<div class="studio-panel ${i===0?'active':''}" data-studio-panel="${esc(v.id)}">${renderView(v,module)}</div>`).join('')}<div class="studio-actions"><button class="button" type="button" data-studio-download>Baixar dados do studio</button><button class="button" type="button" data-studio-copy-all>Copiar resumo</button></div></section>`}

function summarize(module){const studio=studioFor(module);const lines=[`# ${module.number} — ${module.title}`,studio?.intro||''];for(const view of safeItems(studio?.views)){lines.push('',`## ${view.label||view.id}`);if(view.items)for(const item of view.items){if(typeof item==='string')lines.push(`- ${item}`);else lines.push(`- ${item.title}: ${item.text||item.note||item.use||''}`)}if(view.rows)for(const row of view.rows)lines.push(`- ${row.join(' | ')}`);if(view.questions)for(const q of view.questions)lines.push(`- ${q.label}: Sim → ${q.yes}; Não → ${q.no}`)}return lines.join('\n')}

export function bindModuleStudio(root,module,{save,copy,notify}={}){const studio=studioFor(module);if(!studio)return;let saved={};try{saved=JSON.parse(localStorage.getItem(key(module))||'{}')}catch{}state.set(module.id,saved);root.querySelectorAll('[data-studio-tab]').forEach(btn=>btn.addEventListener('click',()=>{const id=btn.dataset.studioTab;root.querySelectorAll('[data-studio-tab]').forEach(x=>x.classList.toggle('active',x===btn));root.querySelectorAll('[data-studio-panel]').forEach(x=>x.classList.toggle('active',x.dataset.studioPanel===id))}));root.querySelectorAll('[data-studio-copy]').forEach(btn=>btn.addEventListener('click',()=>copy?.(decodeURIComponent(btn.dataset.studioCopy||''))));root.querySelectorAll('[data-studio-check]').forEach(input=>input.addEventListener('change',()=>{const s=state.get(module.id)||{};s[input.dataset.studioCheck]=input.checked;state.set(module.id,s);localStorage.setItem(key(module),JSON.stringify(s));notify?.('Checklist salvo')}));root.querySelectorAll('[data-decision-result]').forEach(btn=>btn.addEventListener('click',()=>{const output=root.querySelector(`[data-decision-output="${btn.dataset.decisionIndex}"]`);if(output)output.textContent=decodeURIComponent(btn.dataset.decisionResult||'')}));root.querySelector('[data-studio-download]')?.addEventListener('click',()=>save?.(`${module.extras?.downloadName||module.id}-studio.json`,JSON.stringify({module:module.id,version:'2.0.0',studio,checklist:state.get(module.id)||{}},null,2),'application/json'));root.querySelector('[data-studio-copy-all]')?.addEventListener('click',()=>copy?.(summarize(module)))}
