import { references as registry, moduleResources, frameworkResources } from './reference-registry.js';

export const groups=[['Foundation',1,4],['Language & Narrative',5,7],['Visual Identity',8,15],['Experience',16,18],['AI & Governance',19,20]];
export const editorialTemplates=['Section Cover','Introduction','Principle','Explanation','Example','Do / Don’t','Comparison','Specification','Application','Checklist','Matrix','Timeline','Decision Tree','Gallery / Contact Sheet','Resource / Download','Prompt / AI Recipe','Governance Record'];
export const figmaOrder=['00 — Cover','01 — Introduction','02 — Brand Core','03 — Strategy','04 — Audience','05 — Personality','06 — Verbal Identity','07 — Messaging','08 — Storytelling','09 — Logo','10 — Colors','11 — Typography','12 — Photography','13 — Illustration','14 — Iconography','15 — Graphic Language','16 — Layout','17 — Motion','18 — Sonic','19 — Brand Experience','20 — Brand in Action','21 — AI Guidelines','22 — Governance','23 — Assets','24 — Changelog'];
export const crossCutting=[['Research & Evidence','Toda afirmação estratégica importante registra fonte, data, método e confiança.'],['Accessibility & Inclusion','Linguagem, visual, mídia e materiais digitais consideram acesso e representação.'],['Localization','Definir o que é invariável e o que pode adaptar idioma, cultura, exemplos e formato.'],['Legal & Licensing','Registrar direitos de logo, fontes, fotografia, ilustração, música, naming e ativos de terceiros.'],['Brand Measurement','Converter percepção desejada em indicadores, baseline, cadência e decisões de revisão.'],['Brand Architecture & Naming','Evitar fragmentação quando surgem produtos, programas, eventos, submarcas e parcerias.']];
export const tabs=[['definition','Definição'],['objective','Objetivo'],['questions','Perguntas'],['example','Exemplo'],['template','Modelo vazio'],['presentation','Apresentação']];
export const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const num=m=>String(m.number||'').padStart(2,'0');
export const hero=(title,lead,eyebrow='Brand Framework')=>`<header class="hero"><p class="eyebrow">${esc(eyebrow)}</p><h1>${esc(title)}</h1><p class="lead">${esc(lead)}</p></header>`;

export function markdownModule(module){const lines=[`# ${num(module)} — ${module.title}`,'',module.summary||'','',`## Objetivo do módulo`,'',module.why||''];for(const f of module.fields||[]){lines.push('',`## ${f.name}`,'',`**Definição**`,f.definition||'','',`**Objetivo**`,f.objective||'');if(f.questions?.length)lines.push('',`**Perguntas**`,...f.questions.map(q=>`- ${q}`));lines.push('',`**Exemplo preenchido**`,f.example||'','',`**Modelo vazio**`,'```',f.template||'','```','',`**Apresentação editorial / Figma**`,f.presentation||'');if(f.evidence)lines.push('',`**Evidência recomendada**`,f.evidence)}return lines.join('\n')}

export function normalizeReference(id,data){if(!id)return null;if(typeof id==='object'){const key=id.id||id.key;return {...(key&&registry[key]?registry[key]:{}),...id}}if(registry[id])return {...registry[id],id};const p=data.references?.[id];if(p)return typeof p==='string'?{id,title:id,url:p}:{id,...p};if(/^https?:/.test(id))return{title:id,url:id,kind:'Reference'};return{id,title:String(id).replaceAll('_',' '),kind:'Reference',note:'Referência cadastrada; URL ainda precisa de validação.'}}
export function refsFor(module,data){const ids=[...(module.refs||[]),...(moduleResources[num(module)]||[])];const seen=new Set();return ids.map(id=>normalizeReference(id,data)).filter(r=>r&&!seen.has(r.url||r.id)&&(seen.add(r.url||r.id),true))}
export function frameworkRefs(data){return frameworkResources.map(id=>normalizeReference(id,data)).filter(Boolean)}
export function refCard(r){return `<article class="reference-card"><div><strong>${esc(r.title||r.label||r.id)}</strong><p>${esc(r.note||r.description||'Fonte de referência para este módulo.')}</p><div class="ref-meta"><span class="ref-kind">${esc(r.kind||'Reference')}</span></div></div>${r.url?`<a href="${esc(r.url)}" target="_blank" rel="noreferrer">Abrir ↗</a>`:'<span class="tag">URL pendente</span>'}</article>`}
export function resourceCard(r){return `<article class="resource-card"><div><strong>${esc(r.title)}</strong><p>${esc(r.note||'')}</p><span class="ref-kind">${esc(r.kind||'Resource')}</span></div><a href="${esc(r.url)}" target="_blank" rel="noreferrer">Abrir / baixar ↗</a></article>`}
export function moduleResourceRefs(module,data){return (moduleResources[num(module)]||[]).map(id=>normalizeReference(id,data)).filter(Boolean)}
